namespace DefaultNamespace;

public class Helper
{
    public static string RebuildScript = @"
    DROP SCHEMA IF EXISTS
    private boxes CASCADE;
    CREATE SCHEMA boxes;
    create table if not exists boxes.box
        (
            boxId   integer generated by default as identity,
            name    text,
            size    text,
            description text,
            price   float,
            boxImage    text,
            material    text,
                primary key (boxId)
                );"
}